name: GREEN Image CI

on:
  push:
    branches: [ "cloud-develope" ]
  pull_request:
    branches: [ "cloud-develope" ]
    paths:
      - 'green.html'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile.green --tag ghcr.io/${{ github.repository }}/green-web:$(date +%s)
        docker push ghcr.io/${{ github.repository }}/green-web:$(date +%s)
